/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Mount(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/PopstyleRe.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
        onClick={()=>{props.onSubmit("hi")}}
          name="Mountain_Bottom"
          castShadow
          receiveShadow
          geometry={nodes.Mountain_Bottom.geometry}
          material={materials.Mountain_Bottom}
        />
        <mesh
          name="Mountain_Top"
          castShadow
          receiveShadow
          geometry={nodes.Mountain_Top.geometry}
          material={materials.Mountain_Top}
        />
        <mesh
          name="Ground"
          castShadow
          receiveShadow
          geometry={nodes.Ground.geometry}
          material={materials.Ground}
        />
        <mesh
          name="Ground001"
          castShadow
          receiveShadow
          geometry={nodes.Ground001.geometry}
          material={materials.Ground}
        />
        <group name="StageModel">
          <group name="StageModel_1">
            <group name="StageModel_2">
              <group name="StageModelMeshNode">
                <mesh
                  name="BackgroundScreen"
                  castShadow
                  receiveShadow
                  geometry={nodes.BackgroundScreen.geometry}
                  material={materials.Screen}
                />
                <mesh
                  name="Bars"
                  castShadow
                  receiveShadow
                  geometry={nodes.Bars.geometry}
                  material={materials.Bars}
                />
                <group name="concert-stagemainfinal__0" />
                <mesh
                  name="Cover_Roof"
                  castShadow
                  receiveShadow
                  geometry={nodes.Cover_Roof.geometry}
                  material={materials['Material.005']}
                />
                <mesh
                  name="Lights"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights.geometry}
                  material={materials.Lights}
                />
                <mesh
                  name="Lights001"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights001.geometry}
                  material={materials.Lights}
                />
                <mesh
                  name="Lights002"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights002.geometry}
                  material={materials.Lights}
                />
                <mesh
                  name="Lights003"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights003.geometry}
                  material={materials.Lights}
                />
                <mesh
                  name="Lights004"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights004.geometry}
                  material={materials.Lights}
                />
                <mesh
                  name="Lights005"
                  castShadow
                  receiveShadow
                  geometry={nodes.Lights005.geometry}
                  material={materials.Lights}
                />
                <mesh
                  name="Rim"
                  castShadow
                  receiveShadow
                  geometry={nodes.Rim.geometry}
                  material={materials['Material.003']}
                />
                <mesh
                  name="Rims"
                  castShadow
                  receiveShadow
                  geometry={nodes.Rims.geometry}
                  material={materials.Bars}
                />
                <mesh
                  name="Roof_Down"
                  castShadow
                  receiveShadow
                  geometry={nodes.Roof_Down.geometry}
                  material={materials['Material.006']}
                />
                <mesh
                  name="Speaker_1"
                  castShadow
                  receiveShadow
                  geometry={nodes.Speaker_1.geometry}
                  material={materials.Speaker}
                />
                <mesh
                  name="Speaker_1001"
                  castShadow
                  receiveShadow
                  geometry={nodes.Speaker_1001.geometry}
                  material={materials.Speaker}
                />
                <mesh
                  name="Speaker_2"
                  castShadow
                  receiveShadow
                  geometry={nodes.Speaker_2.geometry}
                  material={materials.Speaker}
                />
                <mesh
                  name="Speaker_2001"
                  castShadow
                  receiveShadow
                  geometry={nodes.Speaker_2001.geometry}
                  material={materials.Speaker}
                />
                <mesh
                  name="Stage"
                  castShadow
                  receiveShadow
                  geometry={nodes.Stage.geometry}
                  material={materials.Stage}
                />
                <mesh
                  name="Stage_Stairs"
                  castShadow
                  receiveShadow
                  geometry={nodes.Stage_Stairs.geometry}
                  material={materials.Stairs}
                />
                <mesh
                  name="Stairs"
                  castShadow
                  receiveShadow
                  geometry={nodes.Stairs.geometry}
                  material={materials.Stage}
                />
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="Stage_Ground"
          castShadow
          receiveShadow
          geometry={nodes.Stage_Ground.geometry}
          material={materials.Stage_Ground}
        />
        <group name="Lamps_Right">
          <mesh
            name="Circle005"
            castShadow
            receiveShadow
            geometry={nodes.Circle005.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Circle005_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle005_1.geometry}
            material={materials['Light.001']}
          />
        </group>
        <group name="Lamps_left">
          <mesh
            name="Circle006"
            castShadow
            receiveShadow
            geometry={nodes.Circle006.geometry}
            material={materials['Material.009']}
          />
          <mesh
            name="Circle006_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle006_1.geometry}
            material={materials['Light.001']}
          />
        </group>
        <group
          name="MainBody"
          position={[-23.175, 4.759, 185.182]}
          rotation={[Math.PI, -0.002, Math.PI]}
          scale={[5.672, 5.508, 5.219]}>
          <mesh
            name="Plane007"
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials.Grey}
          />
          <mesh
            name="Plane007_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_1.geometry}
            material={materials['Grey.001']}
          />
          <mesh
            name="Plane007_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_2.geometry}
            material={materials.Window}
          />
          <mesh
            name="Plane007_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_3.geometry}
            material={materials.Wall}
          />
          <mesh
            name="Plane007_4"
            castShadow
            receiveShadow
            geometry={nodes.Plane007_4.geometry}
            material={materials.Metal}
          />
        </group>
        <group name="Circle" position={[-38.938, 1.041, 176.325]} scale={5.869}>
          <mesh
            name="Circle003"
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials['Grey.002']}
          />
          <mesh
            name="Circle003_1"
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials['Grey.003']}
          />
          <mesh
            name="Circle003_2"
            castShadow
            receiveShadow
            geometry={nodes.Circle003_2.geometry}
            material={materials['Metal.001']}
          />
        </group>
        <mesh
          name="Airport_lane"
          castShadow
          receiveShadow
          geometry={nodes.Airport_lane.geometry}
          material={materials.Stage_Ground}
        />
        <group
          name="Plane019"
          position={[2.282, 0.009, 182.015]}
          rotation={[0, Math.PI / 2, 0]}
          scale={4.657}>
          <mesh
            name="Plane019_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane019_1.geometry}
            material={materials['Grey.004']}
          />
          <mesh
            name="Plane019_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane019_2.geometry}
            material={materials['Ground.001']}
          />
        </group>
        <group
          name="Sketchfab_model"
          position={[176.708, 64.774, 159.894]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.807}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cube_0" position={[-9.875, 13.629, 0.886]} scale={0.534}>
                <group name="Object_4" position={[77.653, 0, -4.884]} scale={0.728}>
                  <mesh
                    name="Object_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0.geometry}
                    material={materials['Material.010']}
                  />
                  <mesh
                    name="Object_0_1"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0_1.geometry}
                    material={materials['Material.011']}
                  />
                  <mesh
                    name="Object_0_2"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_0_2.geometry}
                    material={materials['Material.012']}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Chair" position={[211.95, 0, -16.737]} rotation={[0, -1.563, 0]} scale={2.771}>
          <group name="Circle001" position={[-0.704, -0.009, -0.071]} scale={2.272} />
          <group name="Circle002" position={[-0.704, -0.009, -0.071]} scale={2.272} />
          <group name="Cube003" position={[-0.704, -0.009, -0.071]} scale={2.272} />
          <group name="Cube006" position={[-0.704, -0.009, -0.071]} scale={2.272}>
            <mesh
              name="Cube006_1"
              castShadow
              receiveShadow
              geometry={nodes.Cube006_1.geometry}
              material={materials['Material.013']}
            />
            <mesh
              name="Cube006_2"
              castShadow
              receiveShadow
              geometry={nodes.Cube006_2.geometry}
              material={materials.Bench_main}
            />
          </group>
        </group>
        <group name="Dining_Table" position={[209.946, 0, -13.576]} scale={0.498}>
          <mesh
            name="Table"
            castShadow
            receiveShadow
            geometry={nodes.Table.geometry}
            material={materials['Chair.001']}
            rotation={[0, -0.074, 0]}
            scale={0.933}
          />
        </group>
        <group name="Dining_Table001" position={[209.946, 0, -7.284]} scale={0.498}>
          <mesh
            name="Table001"
            castShadow
            receiveShadow
            geometry={nodes.Table001.geometry}
            material={materials['Chair.001']}
            rotation={[0, -0.074, 0]}
            scale={0.933}
          />
        </group>
        <group name="Dining_Table002" position={[209.946, 0, -1.049]} scale={0.498}>
          <mesh
            name="Table002"
            castShadow
            receiveShadow
            geometry={nodes.Table002.geometry}
            material={materials['Chair.001']}
            rotation={[0, -0.074, 0]}
            scale={0.933}
          />
        </group>
        <group name="Dining_Table003" position={[209.946, 0, 5.35]} scale={0.498}>
          <mesh
            name="Table003"
            castShadow
            receiveShadow
            geometry={nodes.Table003.geometry}
            material={materials['Chair.001']}
            rotation={[0, -0.074, 0]}
            scale={0.933}
          />
        </group>
        <group name="Dining_Table004" position={[209.946, 0, 11.749]} scale={0.498}>
          <mesh
            name="Table004"
            castShadow
            receiveShadow
            geometry={nodes.Table004.geometry}
            material={materials['Chair.001']}
            rotation={[0, -0.074, 0]}
            scale={0.933}
          />
        </group>
        <group name="Dining_Table005" position={[209.946, 0, 17.903]} scale={0.498}>
          <mesh
            name="Table005"
            castShadow
            receiveShadow
            geometry={nodes.Table005.geometry}
            material={materials['Chair.001']}
            rotation={[0, -0.074, 0]}
            scale={0.933}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/PopstyleRe.glb')



